export const data = [
  {
    id: 'iced-coffee',
    name: { pl: 'Kawa mrożona', en: 'Iced Coffee' },
    description: { pl: 'Zimna kawa na bazie cold brew', en: 'Cold brew over ice' },
    ingredients: [
      {
        name: { pl: 'Cold brew', en: 'Cold brew' },
        colors: ['#2b1b0e', '#3a2515', '#472f20', '#5a3b2a', '#6e4c38'],
        contrast: 'dark',
        percentage: 40,
      },
      {
        name: { pl: 'Lód', en: 'Ice' },
        colors: ['#d4e9f2', '#e5f2f9', '#eef7fc', '#f4fbfe', '#ffffff'],
        contrast: 'light',
        percentage: 35,
      },
      {
        name: { pl: 'Woda', en: 'Water' },
        colors: ['#b3e0ff', '#cceaff', '#e6f4ff', '#f2f9ff', '#ffffff'],
        contrast: 'light',
        percentage: 25,
      },
    ],
    price: 4.0,
    available: true,
    tags: ['cold'],
    strength: 2,
    popularity: 4,
  },
  {
    id: 'irish-coffee',
    name: { pl: 'Kawa irlandzka', en: 'Irish Coffee' },
    description: { pl: 'Kawa z whiskey i bitą śmietaną', en: 'Whiskey, coffee, and cream' },
    ingredients: [
      {
        name: { pl: 'Bita śmietana', en: 'Whipped cream' },
        colors: ['#ffffff', '#fdfdfd', '#fbfbfb', '#f8f8f8', '#f5f5f5'],
        contrast: 'light',
        percentage: 20,
      },
      {
        name: { pl: 'Whiskey', en: 'Whiskey' },
        colors: ['#a36f1d', '#c27f21', '#d48f2b', '#e0a142', '#f0b65c'],
        contrast: 'dark',
        percentage: 15,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 25,
      },
      {
        name: { pl: 'Woda', en: 'Water' },
        colors: ['#b3e0ff', '#cceaff', '#e6f4ff', '#f2f9ff', '#ffffff'],
        contrast: 'light',
        percentage: 40,
      },
    ],
    price: 7.0,
    available: true,
    tags: ['alcohol'],
    strength: 3,
    popularity: 2,
  },
  {
    id: 'mokka',
    name: { pl: 'Mokka', en: 'Mocha' },
    description: { pl: 'Kawa z czekoladą', en: 'Chocolate-infused coffee delight' },
    ingredients: [
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 50,
      },
      {
        name: { pl: 'Czekolada', en: 'Chocolate' },
        colors: ['#36200d', '#4a2810', '#5a3214', '#6b3d18', '#7c4820'],
        contrast: 'dark',
        percentage: 20,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 30,
      },
    ],
    price: 5.5,
    available: true,
    tags: ['chocolate'],
    strength: 3,
    popularity: 4,
  },
  {
    id: 'dalgona-coffee',
    name: { pl: 'Dalgona Coffee', en: 'Dalgona Coffee' },
    description: { pl: 'Bita kawa na mleku', en: 'Fluffy whipped coffee over milk' },
    ingredients: [
      {
        name: { pl: 'Spieniona kawa', en: 'Whipped coffee' },
        colors: ['#5a3e2f', '#6d4b37', '#7f5a42', '#93704d', '#a68458'],
        contrast: 'dark',
        percentage: 25,
      },
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#faf5ed', '#fdf9f2', '#ffffff', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 50,
      },
      {
        name: { pl: 'Woda', en: 'Water' },
        colors: ['#b3e0ff', '#cceaff', '#e6f4ff', '#f2f9ff', '#ffffff'],
        contrast: 'light',
        percentage: 25,
      },
    ],
    price: 4.5,
    available: true,
    tags: ['cold'],
    strength: 2,
    popularity: 3,
  },
  {
    id: 'black-coffee',
    name: { pl: 'Kawa czarna', en: 'Black Coffee' },
    description: { pl: 'Klasyczna czarna kawa', en: 'Simple black coffee' },
    ingredients: [
      {
        name: { pl: 'Kawa', en: 'Coffee' },
        colors: ['#3b2d1f', '#4c3825', '#5c442b', '#6d5032', '#7e5c39'],
        contrast: 'dark',
        percentage: 100,
      },
    ],
    price: 3.0,
    available: true,
    tags: ['classic'],
    strength: 3,
    popularity: 5,
  },
  {
    id: 'americano',
    name: { pl: 'Americano', en: 'Americano' },
    description: { pl: 'Espresso z dodatkową wodą', en: 'Espresso diluted with water' },
    ingredients: [
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 50,
      },
      {
        name: { pl: 'Woda', en: 'Water' },
        colors: ['#b3e0ff', '#cceaff', '#e6f4ff', '#f2f9ff', '#ffffff'],
        contrast: 'light',
        percentage: 50,
      },
    ],
    price: 3.5,
    available: true,
    tags: ['classic'],
    strength: 2,
    popularity: 4,
  },
  {
    id: 'flat-white',
    name: { pl: 'Flat White', en: 'Flat White' },
    description: { pl: 'Podwójne espresso z mlekiem', en: 'Double espresso with steamed milk' },
    ingredients: [
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 60,
      },
      {
        name: { pl: 'Spienione mleko', en: 'Steamed milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 40,
      },
    ],
    price: 4.5,
    available: true,
    tags: ['classic', 'milk'],
    strength: 4,
    popularity: 4,
  },
  {
    name: { pl: 'Macchiato', en: 'Macchiato' },
    description: { pl: 'Espresso z odrobiną mleka', en: 'Espresso with a drop of milk' },
    ingredients: [
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 20,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 80,
      },
    ],
    price: 3.5,
    available: true,
    tags: ['classic', 'milk'],
    strength: 4,
    popularity: 3,
  },
  {
    id: 'cafe-au-lait',
    name: { pl: 'Café au lait', en: 'Café au lait' },
    description: { pl: 'Kawa parzona z mlekiem', en: 'Brewed coffee with milk' },
    ingredients: [
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 50,
      },
      {
        name: { pl: 'Kawa parzona', en: 'Brewed coffee' },
        colors: ['#3b2d1f', '#4c3825', '#5c442b', '#6d5032', '#7e5c39'],
        contrast: 'dark',
        percentage: 25,
      },
      {
        name: { pl: 'Woda', en: 'Water' },
        colors: ['#b3e0ff', '#cceaff', '#e6f4ff', '#f2f9ff', '#ffffff'],
        contrast: 'light',
        percentage: 25,
      },
    ],
    price: 4.0,
    available: true,
    tags: ['classic', 'milk'],
    strength: 2,
    popularity: 3,
  },
  {
    id: 'cappuccino',
    name: { pl: 'Cappuccino', en: 'Cappuccino' },
    description: {
      pl: 'Espresso z mlekiem i pianką mleczną',
      en: 'Espresso with steamed milk and milk foam',
    },
    ingredients: [
      {
        name: { pl: 'Spienione mleko', en: 'Milk foam' },
        colors: ['#ffffff', '#fdfdfd', '#fbfbfb', '#f8f8f8', '#f5f5f5'],
        contrast: 'light',
        percentage: 33,
      },
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 34,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 33,
      },
    ],
    price: 4.5,
    available: true,
    tags: ['classic', 'milk'],
    strength: 3,
    popularity: 5,
  },
  {
    id: 'viennese-coffee',
    name: { pl: 'Kawa po wiedeńsku', en: 'Viennese Coffee' },
    description: { pl: 'Espresso z bitą śmietaną', en: 'Espresso with whipped cream' },
    ingredients: [
      {
        name: { pl: 'Bita śmietana', en: 'Whipped cream' },
        colors: ['#ffffff', '#fdfdfd', '#fbfbfb', '#f8f8f8', '#f5f5f5'],
        contrast: 'light',
        percentage: 30,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 70,
      },
    ],
    price: 5.0,
    available: true,
    tags: ['classic', 'sweet'],
    strength: 4,
    popularity: 2,
  },
  {
    id: 'cortado',
    name: { pl: 'Cortado', en: 'Cortado' },
    description: { pl: 'Espresso z małą ilością mleka', en: 'Espresso cut with warm milk' },
    ingredients: [
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 15,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 85,
      },
    ],
    price: 4.0,
    available: true,
    tags: ['classic', 'milk'],
    strength: 4,
    popularity: 2,
  },
  {
    id: 'breve',
    name: { pl: 'Breve', en: 'Breve' },
    description: {
      pl: 'Espresso z pół na pół mlekiem i śmietanką',
      en: 'Espresso with half-and-half',
    },
    ingredients: [
      {
        name: { pl: 'Śmietanka', en: 'Cream' },
        colors: ['#faf5ed', '#fdf9f2', '#ffffff', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 25,
      },
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 25,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 50,
      },
    ],
    price: 4.5,
    available: true,
    tags: ['milk', 'creamy'],
    strength: 3,
    popularity: 2,
  },
  {
    id: 'espresso-con-panna',
    name: { pl: 'Espresso Con Panna', en: 'Espresso Con Panna' },
    description: { pl: 'Espresso z bitą śmietaną', en: 'Espresso topped with whipped cream' },
    ingredients: [
      {
        name: { pl: 'Bita śmietana', en: 'Whipped cream' },
        colors: ['#ffffff', '#fdfdfd', '#fbfbfb', '#f8f8f8', '#f5f5f5'],
        contrast: 'light',
        percentage: 40,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 60,
      },
    ],
    price: 5.0,
    available: true,
    tags: ['sweet', 'classic'],
    strength: 4,
    popularity: 2,
  },
  {
    id: 'cafe-bombon',
    name: { pl: 'Café Bombón', en: 'Café Bombón' },
    description: {
      pl: 'Espresso z mlekiem skondensowanym',
      en: 'Espresso with sweetened condensed milk',
    },
    ingredients: [
      {
        name: { pl: 'Mleko skondensowane', en: 'Condensed milk' },
        colors: ['#f4e5c3', '#f8e8cf', '#fcebdc', '#fef0e8', '#ffffff'],
        contrast: 'light',
        percentage: 25,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 75,
      },
    ],
    price: 5.5,
    available: true,
    tags: ['sweet', 'dessert'],
    strength: 4,
    popularity: 2,
  },
  {
    id: 'marocchino',
    name: { pl: 'Marocchino', en: 'Marocchino' },
    description: { pl: 'Espresso, kakao i mleko', en: 'Espresso with cocoa and milk' },
    ingredients: [
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 30,
      },
      {
        name: { pl: 'Kakao', en: 'Cocoa' },
        colors: ['#3c1e0e', '#4a2810', '#5a3214', '#6b3d18', '#7c4820'],
        contrast: 'dark',
        percentage: 20,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 50,
      },
    ],
    price: 5.5,
    available: true,
    tags: ['chocolate', 'dessert'],
    strength: 3,
    popularity: 2,
  },
  {
    id: 'cold-brew',
    name: { pl: 'Cold Brew', en: 'Cold Brew' },
    description: { pl: 'Zimna kawa macerowana', en: 'Slowly brewed cold coffee' },
    ingredients: [
      {
        name: { pl: 'Cold brew', en: 'Cold brew' },
        colors: ['#2b1b0e', '#3a2515', '#472f20', '#5a3b2a', '#6e4c38'],
        contrast: 'dark',
        percentage: 40,
      },
      {
        name: { pl: 'Woda', en: 'Water' },
        colors: ['#b3e0ff', '#cceaff', '#e6f4ff', '#f2f9ff', '#ffffff'],
        contrast: 'light',
        percentage: 60,
      },
    ],
    price: 4.5,
    available: true,
    tags: ['cold'],
    strength: 4,
    popularity: 3,
  },
  {
    id: 'caffe-corretto',
    name: { pl: 'Caffè corretto', en: 'Caffè corretto' },
    description: { pl: 'Espresso z alkoholem', en: 'Espresso spiked with liquor' },
    ingredients: [
      {
        name: { pl: 'Brandy', en: 'Brandy' },
        colors: ['#a36f1d', '#c27f21', '#d48f2b', '#e0a142', '#f0b65c'],
        contrast: 'dark',
        percentage: 20,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 80,
      },
    ],
    price: 6.5,
    available: true,
    tags: ['alcohol'],
    strength: 4,
    popularity: 1,
  },
  {
    id: 'lungo',
    name: { pl: 'Lungo', en: 'Lungo' },
    description: { pl: 'Espresso z większą ilością wody', en: 'Espresso with more water' },
    ingredients: [
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 30,
      },
      {
        name: { pl: 'Woda', en: 'Water' },
        colors: ['#b3e0ff', '#cceaff', '#e6f4ff', '#f2f9ff', '#ffffff'],
        contrast: 'light',
        percentage: 70,
      },
    ],
    price: 4.0,
    available: true,
    tags: ['classic'],
    strength: 2,
    popularity: 3,
  },
  {
    id: 'red-eye',
    name: { pl: 'Red Eye', en: 'Red Eye' },
    description: {
      pl: 'Kawa parzona z dodatkiem espresso',
      en: 'Drip coffee with an espresso shot',
    },
    ingredients: [
      {
        name: { pl: 'Kawa parzona', en: 'Brewed coffee' },
        colors: ['#3b2d1f', '#4c3825', '#5c442b', '#6d5032', '#7e5c39'],
        contrast: 'dark',
        percentage: 70,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 30,
      },
    ],
    price: 5.0,
    available: true,
    tags: ['strong', 'classic'],
    strength: 5,
    popularity: 2,
  },
  {
    id: 'frappe',
    name: { pl: 'Frappe', en: 'Frappe' },
    description: { pl: 'Mrożona kawa ubijana na piankę', en: 'Foamy iced coffee' },
    ingredients: [
      {
        name: { pl: 'Spieniona kawa', en: 'Whipped coffee' },
        colors: ['#5a3e2f', '#6d4b37', '#7f5a42', '#93704d', '#a68458'],
        contrast: 'dark',
        percentage: 40,
      },
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 30,
      },
      {
        name: { pl: 'Lód', en: 'Ice' },
        colors: ['#d4e9f2', '#e5f2f9', '#eef7fc', '#f4fbfe', '#ffffff'],
        contrast: 'light',
        percentage: 30,
      },
    ],
    price: 5.5,
    available: true,
    tags: ['cold'],
    strength: 2,
    popularity: 3,
  },
  {
    id: 'nitro-coffee',
    name: { pl: 'Nitro Coffee', en: 'Nitro Coffee' },
    description: { pl: 'Cold brew nasycone azotem', en: 'Nitrogen-infused cold brew' },
    ingredients: [
      {
        name: { pl: 'Cold brew z azotem', en: 'Nitrogen-infused cold brew' },
        colors: ['#2b1b0e', '#3a2515', '#472f20', '#5a3b2a', '#6e4c38'],
        contrast: 'dark',
        percentage: 60,
      },
      {
        name: { pl: 'Woda', en: 'Water' },
        colors: ['#b3e0ff', '#cceaff', '#e6f4ff', '#f2f9ff', '#ffffff'],
        contrast: 'light',
        percentage: 40,
      },
    ],
    price: 6.0,
    available: true,
    tags: ['cold'],
    strength: 4,
    popularity: 2,
  },
  {
    id: 'kahlúa-coffee',
    name: { pl: 'Kahlúa Coffee', en: 'Kahlúa Coffee' },
    description: { pl: 'Espresso z likierem kawowym', en: 'Espresso with coffee liqueur' },
    ingredients: [
      {
        name: { pl: 'Likier kawowy', en: 'Coffee liqueur' },
        colors: ['#4c2e1f', '#5a3b2a', '#6b4538', '#7d5845', '#8f6c52'],
        contrast: 'dark',
        percentage: 30,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 70,
      },
    ],
    price: 6.5,
    available: true,
    tags: ['alcohol'],
    strength: 3,
    popularity: 1,
  },
  {
    id: 'bicerin',
    name: { pl: 'Bicerin', en: 'Bicerin' },
    description: {
      pl: 'Warstwowa kawa z czekoladą i śmietanką',
      en: 'Layered coffee with chocolate and cream',
    },
    ingredients: [
      {
        name: { pl: 'Śmietanka', en: 'Cream' },
        colors: ['#faf5ed', '#fdf9f2', '#ffffff', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 20,
      },
      {
        name: { pl: 'Czekolada', en: 'Chocolate' },
        colors: ['#36200d', '#4a2810', '#5a3214', '#6b3d18', '#7c4820'],
        contrast: 'dark',
        percentage: 30,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 50,
      },
    ],
    price: 7.0,
    available: true,
    tags: ['chocolate', 'sweet'],
    strength: 3,
    popularity: 1,
  },
  {
    id: 'espresso',
    name: { pl: 'Espresso', en: 'Espresso' },
    description: { pl: 'Klasyczny espresso', en: 'Classic espresso' },
    ingredients: [
      {
        name: { pl: 'Kawa', en: 'Coffee' },
        colors: ['#3b2d1f', '#4c3825', '#5c442b', '#6d5032', '#7e5c39'],
        contrast: 'dark',
        percentage: 100,
      },
    ],
    price: 3.0,
    available: true,
    tags: ['classic'],
    strength: 4,
    popularity: 4,
  },
  {
    id: 'latte',
    name: { pl: 'Latte', en: 'Latte' },
    description: { pl: 'Espresso z mlekiem', en: 'Espresso with milk' },
    ingredients: [
      {
        name: { pl: 'Mleko', en: 'Milk' },
        colors: ['#f8f4e3', '#fcf8eb', '#fffdf7', '#ffffff', '#ffffff'],
        contrast: 'light',
        percentage: 50,
      },
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 50,
      },
    ],
    price: 4.0,
    available: true,
    tags: ['classic', 'milk'],
    strength: 2,
    popularity: 5,
  },
  {
    id: 'ristretto',
    name: { pl: 'Ristretto', en: 'Ristretto' },
    description: { pl: 'Skoncentrowane espresso', en: 'Concentrated espresso' },
    ingredients: [
      {
        name: { pl: 'Espresso', en: 'Espresso' },
        colors: ['#402d20', '#4f3727', '#583d2b', '#634632', '#6f4d36'],
        contrast: 'dark',
        percentage: 100,
      },
    ],
    price: 3.5,
    available: true,
    tags: ['classic'],
    strength: 4,
    popularity: 2,
  },
]
